FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash mule

RUN mkdir /etc/mule

RUN mkdir /var/lib/mule

RUN chown mule:mule /etc/mule /var/lib/mule

WORKDIR /home/mule

COPY --chown=mule:mule linux64/* ./run.sh /home/mule/

USER mule

CMD ["/home/mule/run.sh"]
